apiVersion: v1
data:
  resource.customizations.health.argoproj.io_Application: |
    if obj.metadata.annotations ~= nil then
        if obj.metadata.annotations["argocd.argoproj.io/enable-health-check"] == "true" then
            hs = {}
            hs.status = "Progressing"
            hs.message = ""
            if obj.status ~= nil then
                if obj.status.health ~= nil then
                    hs.status = obj.status.health.status
                    if obj.status.health.message ~= nil then
                        hs.message = obj.status.health.message
                    end
                end
            end
            return hs
        end
    end
    hs = {}
    hs.status = "Healthy"
    hs.message = "health check is not enabled for this application"
    return hs
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd
