apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: swica-stages
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: prod
  template:
    metadata:
      name: 'swica-{{stage}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/chaehni/hat_testing.git
        targetRevision: master
        path: 'argocd/apps/swica/{{stage}}'
        directory:
          recurse: true
          include: '{prod/shp-api-gateway/*,{{stage}}/post_hook.yaml,{{stage}}/sync_failed.yaml }'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true