apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: client-stages
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - stage: prod
  template:
    metadata:
      name: 'client-{{stage}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/chaehni/hat_testing.git
        targetRevision: master
        path: 'argocd/apps/client/{{stage}}'
        directory:
          recurse: true
          include: '{shp-api-gateway/*.yaml,shp-data-platform/*.yaml,post_hook.yaml,sync_failed.yaml}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true