apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: hello-task
spec:
  params:
    - name: username
      type: string
  steps:
    - name: greet
      image: alpine
      script: |
        #!/bin/sh
        echo "Hello from $(params.username)"