apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: swica-prod-apps
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - component: backend
  template:
    metadata:
      name: 'swica-prod-user-service-backend-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/chaehni/hat_testing.git
        targetRevision: master
        path: 'argocd/apps/swica/prod/user-service/{{component}}'
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true