apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: client-prod-user-service-backend
  namespace: argocd
  annotations:
    argocd.argoproj.io/enable-health-check: "true"
spec:
  project: client-prod-project
  sources:
    - repoURL: 'https://github.com/chaehni/hat_testing'
      path: helm/user-service
      targetRevision: master
      helm:
        parameters:
        - name: image.tag
          value: latest
        valueFiles:
        - $values/values/client_values.yaml
    - repoURL: 'https://github.com/chaehni/hat_testing'
      targetRevision: master
      ref: values
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: service-backend
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  info:
  - name: key
    value: value