apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swica-prod-user-service-backend-component
  namespace: argocd
  annotations:
    key: values 
spec:
  project: swica-prod-project
  sources:
    - repoURL: 'https://github.com/chaehni/hat_testing'
      path: helm/user-service
      targetRevision: master
      helm:
        parameters:
        - name: image.tag
          value: garbage
        valueFiles:
        - $values/values/swica_values.yaml
    - repoURL: 'https://github.com/chaehni/hat_testing'
      targetRevision: master
      ref: values
    - repoURL: https://github.com/chaehni/hat_testing.git
      targetRevision: master
      path: 'argocd/apps/swica/prod'
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: swica-prod
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
  info:
  - name: key
    value: value