apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: root
  namespace: argocd
spec:
  generators:
  - list:
      elements:
      - folder: apps
      - folder: projects
  template:
    metadata:
      name: '{{folder}}-app'
    spec:
      project: default
      source:
        repoURL: https://github.com/chaehni/hat_testing.git
        targetRevision: master
        path: argocd/{{folder}}
      destination:
        server: https://kubernetes.default.svc
      syncPolicy:
        automated:
          selfHeal: true