apiVersion: batch/v1
kind: Job
metadata:
  generateName: tekton-trigger-hook-
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  template:
    spec:
      containers:
      - name: curl
        image: curlimages/curl
        command:
          - "curl"
          - "-X"
          - "POST"
          - "-H"
          - "Content-Type: application/json"
          - "-d"
          - '{"username": "ArgoCD"}'
          - "http://10.244.0.110:8080"
      restartPolicy: Never
  backoffLimit: 2